#!/bin/bash

# Ultra final script for last remaining comments

FILE="assets/widgets/vectors/operations.html"

# Last remaining comments
sed -i '' 's|// Только если точки нет - создаем новую|// Only if point does not exist - create new one|g' "$FILE"
sed -i '' 's|// Если найден идентичный вектор, используем его|// If identical vector found, use it|g' "$FILE"
sed -i '' 's|// Добавляем к информации об операции|// Add to operation information|g' "$FILE"
sed -i '' 's|// Если это второй метод, показываем мигание|// If this is second method, show blinking|g' "$FILE"
sed -i '' 's|// Для вычитания, если vector2 уже имеет минус (операционный вектор -b)|// For subtraction, if vector2 already has minus (operation vector -b)|g' "$FILE"
sed -i '' 's|// Убираем минус из имени второго вектора и используем обычную логику a-b|// Remove minus from second vector name and use normal a-b logic|g' "$FILE"
sed -i '' 's|// Убираем первый символ \x27-\x27|// Remove first character \x27-\x27|g' "$FILE"
sed -i '' 's|// Для треугольника: создаем вектор с существующими точками|// For triangle: create vector with existing points|g' "$FILE"
sed -i '' 's|// Используем существующую начальную точку|// Use existing start point|g' "$FILE"
sed -i '' 's|// Используем существующую конечную точку|// Use existing end point|g' "$FILE"
sed -i '' 's|// Для параллелограмма: создаем вектор от startPoint до resultEnd|// For parallelogram: create vector from startPoint to resultEnd|g' "$FILE"
sed -i '' 's|// Результирующий вектор должен быть помечен как зависимый от операции|// Result vector should be marked as dependent on operation|g' "$FILE"
sed -i '' 's|// Рисование векторов|// Drawing vectors|g' "$FILE"
sed -i '' 's|// Выбранный вектор должен подсвечиваться|// Selected vector should be highlighted|g' "$FILE"
sed -i '' 's|// Проверяем выбран ли вектор для операций|// Check if vector is selected for operations|g' "$FILE"
sed -i '' 's|// Подсветка выбранного вектора|// Highlighting selected vector|g' "$FILE"
sed -i '' 's|// Рисуем более толстую линию для выбранного вектора|// Draw thicker line for selected vector|g' "$FILE"
sed -i '' 's|// Основная линия вектора|// Main vector line|g' "$FILE"
sed -i '' 's|// Стрелка вектора|// Vector arrow|g' "$FILE"
sed -i '' 's|// Вычисляем угол вектора|// Calculate vector angle|g' "$FILE"
sed -i '' 's|// Размер стрелки|// Arrow size|g' "$FILE"
sed -i '' 's|// Вычисляем точки стрелки|// Calculate arrow points|g' "$FILE"
sed -i '' 's|// Рисуем стрелку|// Draw arrow|g' "$FILE"

# Handle function and class comments
sed -i '' 's|// Функция отрисовки|// Drawing function|g' "$FILE"
sed -i '' 's|// Функция отрисовки сетки|// Grid drawing function|g' "$FILE"
sed -i '' 's|// Функция отрисовки осей|// Axes drawing function|g' "$FILE"
sed -i '' 's|// Функция отрисовки вектора|// Vector drawing function|g' "$FILE"
sed -i '' 's|// Функция отрисовки точки|// Point drawing function|g' "$FILE"
sed -i '' 's|// Функция отрисовки подписи|// Label drawing function|g' "$FILE"
sed -i '' 's|// Функция получения координат точки|// Function to get point coordinates|g' "$FILE"
sed -i '' 's|// Функция получения координат вектора|// Function to get vector coordinates|g' "$FILE"
sed -i '' 's|// Обработчики событий|// Event handlers|g' "$FILE"
sed -i '' 's|// Обработчик клика мыши|// Mouse click handler|g' "$FILE"
sed -i '' 's|// Обработчик движения мыши|// Mouse move handler|g' "$FILE"
sed -i '' 's|// Проверяем клик по вектору|// Check click on vector|g' "$FILE"
sed -i '' 's|// Проверяем клик по точке|// Check click on point|g' "$FILE"
sed -i '' 's|// Проверяем клик по пустому месту|// Check click on empty space|g' "$FILE"

echo "Ultra final translation completed."
echo "Remaining Russian text lines:"
grep -c "[а-яё]" "$FILE"
echo "Remaining Russian comment lines:"
grep -c "//.*[а-яё]" "$FILE"