#!/bin/bash

# Final script to translate remaining Russian comments

FILE="assets/widgets/vectors/operations.html"

# Fix the broken line from previous script
sed -i '' 's|// Stop animation если идет|// Stop animation if running|g' "$FILE"

# Remaining specific comments
sed -i '' 's|// Переменные для анимации операций|// Variables for operation animations|g' "$FILE"
sed -i '' 's|// ИСПРАВЛЕННЫЕ ВЫЧИСЛЕНИЯ:|// CORRECTED CALCULATIONS:|g' "$FILE"
sed -i '' 's|// 1. Линия от конца первого вектора параллельно перемещенному второму вектору|// 1. Line from end of first vector parallel to moved second vector|g' "$FILE"
sed -i '' 's|// 2. Линия от конца перемещенного второго вектора параллельно первому вектору|// 2. Line from end of moved second vector parallel to first vector|g' "$FILE"
sed -i '' 's|// Проверяем, не совпадают ли линии (с учетом погрешности вычислений)|// Check if lines coincide (considering calculation tolerance)|g' "$FILE"
sed -i '' 's|// Допустимая погрешность в пикселях|// Acceptable tolerance in pixels|g' "$FILE"
sed -i '' 's|// Добавляем первую сторону параллелограмма|// Add first side of parallelogram|g' "$FILE"
sed -i '' 's|// Первая линия сразу|// First line immediately|g' "$FILE"
sed -i '' 's|// Время первой анимации|// First animation time|g' "$FILE"
sed -i '' 's|// Добавляем вторую линию только если она отличается от первой|// Add second line only if it differs from first|g' "$FILE"
sed -i '' 's|// Вторая линия с задержкой 1000мс|// Second line with 1000ms delay|g' "$FILE"
sed -i '' 's|// Вызываем callback после завершения всех анимаций|// Call callback after all animations complete|g' "$FILE"
sed -i '' 's|// Для начальной точки: ВСЕГДА используем существующую точку startPoint первого вектора|// For start point: ALWAYS use existing startPoint of first vector|g' "$FILE"
sed -i '' 's|// УНИФИЦИРОВАННАЯ ЛОГИКА: ищем существующие точки, не создаем новые|// UNIFIED LOGIC: search existing points, do not create new ones|g' "$FILE"
sed -i '' 's|// Для треугольника: используем СУЩЕСТВУЮЩУЮ конечную точку второго вектора|// For triangle: use EXISTING end point of second vector|g' "$FILE"
sed -i '' 's|// ✅ Используем сам объект точки, а не копию координат|// ✅ Use point object itself, not coordinate copy|g' "$FILE"
sed -i '' 's|// ✅ Используем существующее имя точки|// ✅ Use existing point name|g' "$FILE"
sed -i '' 's|// Для параллелограмма: вычисляем диагональ|// For parallelogram: calculate diagonal|g' "$FILE"
sed -i '' 's|// ИЩЕМ СУЩЕСТВУЮЩУЮ ТОЧКУ с такими координатами|// SEARCH FOR EXISTING POINT with such coordinates|g' "$FILE"
sed -i '' 's|// Используем существующую точку и ее имя|// Use existing point and its name|g' "$FILE"

# More remaining comments
sed -i '' 's|// Создаем новую точку для результата|// Create new point for result|g' "$FILE"
sed -i '' 's|// Добавляем новую точку в массив|// Add new point to array|g' "$FILE"
sed -i '' 's|// Создаем результирующий вектор|// Create result vector|g' "$FILE"
sed -i '' 's|// Результирующий вектор соединяет начальную точку первого вектора с конечной точкой|// Result vector connects start point of first vector with end point|g' "$FILE"
sed -i '' 's|// Удаляем дублирующие точки после операции|// Remove duplicate points after operation|g' "$FILE"
sed -i '' 's|// Создание и анимированное появление копии вектора|// Creation and animated appearance of vector copy|g' "$FILE"
sed -i '' 's|// Создаем анимированную копию вектора b в начале координат|// Create animated copy of vector b at origin|g' "$FILE"
sed -i '' 's|// Плавная анимация перемещения вектора|// Smooth vector movement animation|g' "$FILE"
sed -i '' 's|// Вычисляем текущую позицию на основе прогресса анимации|// Calculate current position based on animation progress|g' "$FILE"
sed -i '' 's|// Обновляем позицию начальной точки|// Update start point position|g' "$FILE"
sed -i '' 's|// Обновляем позицию конечной точки|// Update end point position|g' "$FILE"
sed -i '' 's|// Когда анимация завершена|// When animation is complete|g' "$FILE"
sed -i '' 's|// Точно устанавливаем финальные координаты|// Precisely set final coordinates|g' "$FILE"
sed -i '' 's|// Сеточка|// Grid|g' "$FILE"
sed -i '' 's|// Оси координат|// Coordinate axes|g' "$FILE"
sed -i '' 's|// Отрисовка основных линий сетки|// Draw main grid lines|g' "$FILE"
sed -i '' 's|// Отрисовка мелких линий сетки|// Draw minor grid lines|g' "$FILE"
sed -i '' 's|// Рисуем горизонтальные линии сетки|// Draw horizontal grid lines|g' "$FILE"
sed -i '' 's|// Рисуем вертикальные линии сетки|// Draw vertical grid lines|g' "$FILE"
sed -i '' 's|// Оси должны быть поверх сетки|// Axes should be above grid|g' "$FILE"
sed -i '' 's|// Ось X|// X axis|g' "$FILE"
sed -i '' 's|// Ось Y|// Y axis|g' "$FILE"
sed -i '' 's|// Стрелки осей|// Axis arrows|g' "$FILE"
sed -i '' 's|// Подписи осей|// Axis labels|g' "$FILE"

echo "Final translation completed."
echo "Remaining Russian text lines:"
grep -c "[а-яё]" "$FILE"