#!/bin/bash

# Extended script to translate remaining Russian comments

FILE="assets/widgets/vectors/operations.html"

# More JavaScript comments translations
sed -i '' 's|// Без Shift - обычное выделение одного вектора (очищаем выбор для операций)|// Without Shift - normal selection of one vector (clear selection for operations)|g' "$FILE"
sed -i '' 's|// НЕ очищаем selectedVectors - позволяем пользователю выбирать без сброса|// DO NOT clear selectedVectors - allow user to select without reset|g' "$FILE"
sed -i '' 's|// С Shift - добавляем/убираем из выбранных для операций|// With Shift - add/remove from selected for operations|g' "$FILE"
sed -i '' 's|// Вектор уже выбран - убираем его|// Vector already selected - remove it|g' "$FILE"
sed -i '' 's|// Вектор не выбран - добавляем|// Vector not selected - add it|g' "$FILE"
sed -i '' 's|// Уже выбрано 2 вектора - заменяем первый|// Already selected 2 vectors - replace first|g' "$FILE"
sed -i '' 's|// Функции для анимированных операций|// Functions for animated operations|g' "$FILE"
sed -i '' 's|// Удаляем векторы операций|// Remove operation vectors|g' "$FILE"
sed -i '' 's|// Удаляем точки операций из общего массива|// Remove operation points from main array|g' "$FILE"
sed -i '' 's|// Останавливаем анимацию если идет|// Stop animation if running|g' "$FILE"
sed -i '' 's|// Не создаем новую точку - используем временные координаты без добавления в points|// Do not create new point - use temporary coordinates without adding to points|g' "$FILE"
sed -i '' 's|// Нет имени для временной точки|// No name for temporary point|g' "$FILE"
sed -i '' 's|// Не является настоящей точкой|// Not a real point|g' "$FILE"
sed -i '' 's|// Добавляем только реальные точки с именами|// Add only real points with names|g' "$FILE"
sed -i '' 's|// Операционные векторы независимы|// Operation vectors are independent|g' "$FILE"
sed -i '' 's|// Плавная интерполяция (easing)|// Smooth interpolation (easing)|g' "$FILE"
sed -i '' 's|// Анимированное появление линии|// Animated line appearance|g' "$FILE"
sed -i '' 's|// Сбрасываем пунктир|// Reset dash|g' "$FILE"
sed -i '' 's|// Функция для сравнения линий с учетом погрешности (та же, что в addAnimatedLine)|// Function to compare lines with tolerance (same as in addAnimatedLine)|g' "$FILE"
sed -i '' 's|// Рисуем статичные линии (только те, что не находятся в процессе анимации)|// Draw static lines (only those not being animated)|g' "$FILE"
sed -i '' 's|// Проверяем, что эта линия не анимируется сейчас (С УЧЕТОМ ПОГРЕШНОСТИ!)|// Check that this line is not being animated now (WITH TOLERANCE!)|g' "$FILE"
sed -i '' 's|// Рисуем анимированные линии с их индивидуальным прогрессом|// Draw animated lines with their individual progress|g' "$FILE"
sed -i '' 's|// ✅ Используем индивидуальный progress|// ✅ Use individual progress|g' "$FILE"
sed -i '' 's|// Новая функция для анимированного добавления вспомогательных линий|// New function for animated addition of auxiliary lines|g' "$FILE"
sed -i '' 's|// Функция для сравнения линий с учетом погрешности|// Function to compare lines with tolerance|g' "$FILE"
sed -i '' 's|// Проверяем, что такой линии еще нет в операционных линиях (с учетом погрешности)|// Check that such line does not exist in operation lines (with tolerance)|g' "$FILE"
sed -i '' 's|// Проверяем, что такой линии еще нет в анимированных (с учетом погрешности)|// Check that such line does not exist in animated (with tolerance)|g' "$FILE"
sed -i '' 's|// Не добавляем дублирующую линию|// Do not add duplicate line|g' "$FILE"
sed -i '' 's|// Создаем объект линии с собственным прогрессом|// Create line object with own progress|g' "$FILE"
sed -i '' 's|// ✅ Индивидуальный прогресс для каждой линии|// ✅ Individual progress for each line|g' "$FILE"
sed -i '' 's|// Анимируем появление линии|// Animate line appearance|g' "$FILE"
sed -i '' 's|// 1.5 секунды на построение линии|// 1.5 seconds to build line|g' "$FILE"
sed -i '' 's|// ✅ Обновляем только свой прогресс|// ✅ Update only own progress|g' "$FILE"
sed -i '' 's|// Правильно удаляем из анимированных и переносим в обычные линии|// Properly remove from animated and move to regular lines|g' "$FILE"
sed -i '' 's|// Добавляем в статичные линии только если её там еще нет|// Add to static lines only if not already there|g' "$FILE"
sed -i '' 's|// Добавляем простой объект без progress|// Add simple object without progress|g' "$FILE"
sed -i '' 's|// Функция для анимированного разворота вектора на 180 градусов|// Function for animated 180-degree vector rotation|g' "$FILE"
sed -i '' 's|// Вычисляем промежуточную позицию конца вектора при развороте|// Calculate intermediate position of vector end during rotation|g' "$FILE"
sed -i '' 's|// Разворот происходит вокруг начальной точки|// Rotation happens around start point|g' "$FILE"
sed -i '' 's|// От 0 до π (180 градусов)|// From 0 to π (180 degrees)|g' "$FILE"
sed -i '' 's|// Применяем поворот вокруг начальной точки|// Apply rotation around start point|g' "$FILE"
sed -i '' 's|// Обновляем конечную точку вектора|// Update vector end point|g' "$FILE"
sed -i '' 's|// Завершаем анимацию|// Complete animation|g' "$FILE"
sed -i '' 's|// ОБЕРТКИ ДЛЯ СОВМЕСТИМОСТИ|// WRAPPERS FOR COMPATIBILITY|g' "$FILE"
sed -i '' 's|// УНИВЕРСАЛЬНАЯ ФУНКЦИЯ ДЛЯ ОПЕРАЦИЙ С ВЕКТОРАМИ|// UNIVERSAL FUNCTION FOR VECTOR OPERATIONS|g' "$FILE"
sed -i '' 's|// Проверяем, выполняется ли та же операция другим методом|// Check if same operation is performed by different method|g' "$FILE"
sed -i '' 's|// Новая операция - очищаем предыдущие результаты|// New operation - clear previous results|g' "$FILE"
sed -i '' 's|// Этап 1: Создаем копию второго вектора (обычную или обращенную)|// Step 1: Create copy of second vector (normal or inverted)|g' "$FILE"
sed -i '' 's|// Для вычитания: сначала создаем копию, затем разворачиваем|// For subtraction: first create copy, then rotate|g' "$FILE"
sed -i '' 's|// Анимируем разворот вектора на 180 градусов|// Animate 180-degree vector rotation|g' "$FILE"
sed -i '' 's|// После разворота меняем имя на -b|// After rotation change name to -b|g' "$FILE"
sed -i '' 's|// Для сложения: создаем обычную копию|// For addition: create normal copy|g' "$FILE"
sed -i '' 's|// Этап 2: Перемещаем операционный вектор к первому вектору|// Step 2: Move operation vector to first vector|g' "$FILE"
sed -i '' 's|// Этап 3: Строим геометрическую фигуру|// Step 3: Build geometric figure|g' "$FILE"
sed -i '' 's|// Этап 4: Строим результирующий вектор|// Step 4: Build result vector|g' "$FILE"
sed -i '' 's|// Без задержки|// Without delay|g' "$FILE"
sed -i '' 's|// Вызываем callback после завершения анимации|// Call callback after animation completion|g' "$FILE"
sed -i '' 's|// Время анимации линии|// Line animation time|g' "$FILE"
sed -i '' 's|// Для параллелограмма строим недостающие стороны с задержкой|// For parallelogram build missing sides with delay|g' "$FILE"

echo "Extended translation completed."
echo "Remaining Russian text lines:"
grep -c "[а-яё]" "$FILE"